In [1]:
import pandas as pd
import numpy as np

In [4]:
resep = pd.read_csv("Results_sep.csv")
resoct = pd.read_csv("Results.csv")
renov = pd.read_csv("Results_nov.csv")

    Unnamed: 0    0    1    2    3    4    5    6    7    8    9   10
0            0  623  413  383  404  403  341  317  463  367  335  452
1            1  691  333  377  426  346  396  288  367  390  270  362
2            2  609  277  415  355  451  253  397  313  386  275  315
3            3  772  549  372  270  391  469  372  405  360  279  438
4            4  602  393  393  444  308  333  399  364  380  470  414
5            5  670  440  333  240  493  497  476  426  314  185  347
6            6  538  266  403  253  276  323  237  326  340  221  224
7            7  472  211  161  253  245  227  268  150  266  194  176
8            8  734  389  373  162  219  404  393  301  169  319  264
9            9  676  269  272  266  434  330  244  327  311  367  352
10          10  555  337  207  266  350  267  311  258  256  260  325
11          11  611  445  439  435  397  441  353  396  493  398  438